### ISSUE TITLE
Crash se nome è composto solo da puntini ("............")

### ISSUE THREAD

**Issue by sarbyn** [kamaladafrica/codice-fiscale#10]
Se durante il calcolo del codice fiscale si inserisce un nome o un cognome composto da soli caratteri '.', la lib va in crash con un IndexOutOfBoundException

**Comment by kamaladafrica** [comment]
Che vada in crash credo sia corretto. Il tipo dell'eccezione sicuramente no. 
Credo che bisognerebbe fare una sorta di validazione prima del calcolo.

**Comment by kamaladafrica** [comment]
Chiudo per inattvità
