### ISSUE TITLE
esteri.csv is read with a wrong encoding

### ISSUE THREAD

**Issue by PepeExpress** [kamaladafrica/codice-fiscale#25]
**Describe the bug**
The file `esteri.csv` gets read with a wrong encoding, this causes to have some replacement characters `�` for certain letters (for example the `ù` of Perù)

**To Reproduce**
1. Given codice fiscale `RSSMRA88D12Z611J`
2. When CodiceFiscale.of("RSSMRA88D12Z611J").getBelfiore().getCity()
3. Returns PER�

**Expected behavior**
Instead PERÙ should be returned.

I will open a pull request with a fix for this

**Comment by kamaladafrica** [comment]
The issue is not in reading, but in the encoding of esteri.csv: that file should be encoded UTF-8 instead of WINDOWS-1252.
So in order to fix the issue, file esteri.csv should be converted to UTF-8.
I'm going to fix it.

**Comment by PepeExpress** [comment]
Ok thanks 👍🏼
