### ISSUE TITLE
codici belfiore mancanti

### ISSUE THREAD

**Issue by emish89** [kamaladafrica/codice-fiscale#4]
Ciao, ho visto che ci sono dei codici di 4 lettere mancanti, tipo I459 e altri.
Tu hai uno script di aggiornamento o li aggiungi a mano?
Se mi spieghi come, posso fare una PR per correggere il problema :)

**Comment by kamaladafrica** [comment]
Ciao, non c'è nessuno script: è semplicemente il file csv con la lista dei comuni scaricato dal sito dell'istat a questo indirizzo
https://www.istat.it/it/archivio/6789#Elencodeicodiciedelledenominazionidelleunitterritoriali-0

Ho appena verificato che purtroppo in quel file mancano i comuni soppressi come Sassocorvaro (I459). Inoltre sul sito dell'istat c'è la lista dei comuni soppressi, ma senza i codici catastali.

Per cui sarebbe opportuno cambiare sorgente dati. Ho individuato un paio di alternative da valutare.

1. Fonte Ministero dell'Interno - https://www.anpr.interno.it/portale/tabelle-di-riferimento (documento codice 03), anche scaricabile da https://github.com/italia/anpr/blob/master/src/archivi/ANPR_archivio_comuni.csv)
2. Fonte Agenzia delle Entrate - https://sister.agenziaentrate.gov.it/CitizenArCom/index.jsp

La 1. contiene un elenco completo di tutte le variazioni, quindi lo stesso comune con lo stesso codice catastale compare più volte nella lista. Bisognerebbe bonificare la lista eliminando i comuni duplicati.

La 2. contiene i link per scaricare i due file separati dei comuni attualmente in essere e quello dei comuni soppressi. Andrebbero quindi fusi in unico file tenendo presente che non sono dello stesso formato (colonne diverse).

Io direi che la fonte numero 1 sia quella migliore. Se ne conosci una migliore valutiamola.

**Comment by kamaladafrica** [comment]
Utilizzando la fonte 1. si potrebbe fare uno script tipo questo che elimina le righe duplicate e le colonne che non servono:
```bash
$ curl https://raw.githubusercontent.com/italia/anpr/master/src/archivi/ANPR_archivio_comuni.csv | awk -F, 'BEGIN{OFS = ","}{print $5,$6,$15}' | uniq > ANPR_archivio_comuni.csv
```
Dopo di che va adattato e rinominato il supplier: https://github.com/kamaladafrica/codice-fiscale/blob/master/src/main/java/it/kamaladafrica/codicefiscale/city/impl/IstatCsvSupplier.java
