### ISSUE TITLE
Errore su chiamata CodiceFiscale.of(cfString) in caso di omocodia

### ISSUE THREAD

**Issue by Mizar01** [kamaladafrica/codice-fiscale#6]
In caso di omocodia (che impatta sui 4 caratteri del comune di nascita), il metodo:

```
CodiceFiscale of(String value, CityByBelfiore provider) {
     ...
     Validate.isTrue(Objects.equals(result.getValue(), value), "expected %s, but found %s", new Object[]{value, result.getValue()});
     ...}
```

fallisce sempre in corrispondenza del 'Validate.isTrue()'

Infatti il valore del codice fiscale iniziale e quello calcolato (normalizzato per omocodia) non saranno mai uguali.

Ho provato sia con un dummyProvider che con il provider di default di CityProvider, ma la normalizzazione è indipendente da questo.

**Comment by kamaladafrica** [comment]
Quella chiamata verifica solamente che l'oggetto `CodiceFiscale` rappresenti correttamente il codice fiscale in formato stringa passato al metodo.
In un test viene utilizzato proprio il metodo che non ti funziona:
https://github.com/kamaladafrica/codice-fiscale/blob/85d292ce4177f7d85ad9c7b747c36d650e64c6a2/src/test/java/it/kamaladafrica/codicefiscale/CodiceFiscaleTest.java#L20-L25

Se il caso che va in errore è differente, ti chiederei lo stacktrace dell'eccezione e il codice fiscale che non ti funziona.

**Comment by Mizar01** [comment]
Ciao. 
Ho approfondito la questione.
Al momento non ho un codice fiscale che posso esporti qui con il problema, ma il cf che fallisce ha nel comune la seguente:

Z1N9

che diventerebbe Z129 trasformato. 
La trasformazione fatta da belfiore è corretta, tuttavia non setta l'omocode corretto (che rimane a 0).

`OmocodeLevel.level(cf, indexes) = 0  -> dovrebbe essere > 0`

Il problema è che il metodo level si ferma al primo carattere numerico trovato a partire dalla fine del codice. trovando subito un 9, il valore tornato è 0.

Forse non è stata considerata questa eventualità. Se digito il cf nel sito di agenzia delle entrate, mi dice che il cf è valido.

**Comment by kamaladafrica** [comment]
Chiuso per inattività

**Comment by albert0m** [comment]
Ho lo stesso identico problema, ho riscontrato il caso in cui il codice del comune presenta una N centrale e non riesce quindi a generare l’oggetto. (Codice comune originale D325, trovato nel codice fiscale D3N5)

**Comment by kamaladafrica** [comment]
Puoi darmi il codice fiscale o generarne uno che presenti lo stesso problema?
Dimmi anche quale operazione in particolare ti da errore (stai decodificando un CF?)

**Comment by albert0m** [comment]
posso mandartelo in privato? è un codice fiscale reale. Semplicemente chiamo la CodiceFiscale.of("str") e mi va in eccezione dicendo "expected %s, but found %s" (dove l'expected contiene il codice del comune corretto e found contiene quello originale)

**Comment by kamaladafrica** [comment]
Se riesci a generarne uno valido di test e' meglio, così lo aggiungiamo cone testcase.
Io comunque non so quando riuscirò a metterci mano, se hai tu o qualcun altro una correzione pronta, potete aprire una PR
