### ISSUE TITLE
JCenter deprecated

### ISSUE THREAD

**Issue by sarbyn** [kamaladafrica/codice-fiscale#9]
Dato che il repo jcenter verrà deprecato a breve, c'è la possibilità che il progetto venga pubblicato altrove?

**Comment by namero999** [comment]
Mi accodo alla richiesta :)

**Comment by kamaladafrica** [comment]
Ciao ragazzi, lo farei volentieri ma non ho il tempo di capire come si possa fare al momento.
Se qualcuno di voi può studiare il modo di farlo, lo faccio volentieri.

**Comment by namero999** [comment]
Ok, grazie, provero' a darci un'occhiata a breve.

**Comment by sarbyn** [comment]
Può valer la pena usare https://jitpack.io/
Fa tutto lui

**Comment by kamaladafrica** [comment]
L'ho usato in passato ed è molto valido, ma vorrei evitare Jitpack perché mi costringe a cambiare il groupId nel pom

**Comment by kamaladafrica** [comment]
Dalla versione 1.3.0 appena rilasciata, la libreria è disponibile su maven central:
```xml
<dependency>
  <groupId>it.kamaladafrica</groupId>
  <artifactId>codice-fiscale</artifactId>
  <version>1.3.0</version>
</dependency>
```
